<a href="https://colab.research.google.com/github/susankhan1/CensusCrimePublicSchools/blob/main/Cities.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import pandas as pd
d={"Mouse":[150,200,300,400],
   "Keyboard":[180,200,190,300],
   "Scanner":[200,280,330,450]}
df=pd.DataFrame(d,index=["Jan","Feb","March","April"])
df

       Mouse  Keyboard  Scanner
Jan      150       180      200
Feb      200       200      280
March    300       190      330
April    400       300      450

In [14]:
#Write code to access data of Mouse and Scanner columns.
df[['Mouse','Scanner']]

       Mouse  Scanner
Jan      150      200
Feb      200      280
March    300      330
April    400      450

In [20]:
#Write code to access data of the Keyboard column using dot notation and column name.
df.Keyboard

Jan      180
Feb      200
March    190
April    300
Name: Keyboard, dtype: int64

In [21]:
#Write code to access data of scanners using loc[].
df.loc[:,['Scanner']]

       Scanner
Jan        200
Feb        280
March      330
April      450

In [25]:
#Write code to access data of all columns where mouse data is more than 200.
df.Mouse > 200

Jan      False
Feb      False
March     True
April     True
Name: Mouse, dtype: bool

In [26]:
#Write code to access columns using 0 and 2.
df.iloc[:,0:2]

       Mouse  Keyboard
Jan      150       180
Feb      200       200
March    300       190
April    400       300

In [28]:
#Write code to access data of rows of jan and march for scanner and keyboard
df.loc[['Jan','March'],['Keyboard','Scanner']]

       Keyboard  Scanner
Jan         180      200
March       190      330